# Generated by Django 3.2.16 on 2024-08-07 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('image', models.ImageField(blank=True, null=True, upload_to='catgory/%Y/%m/%d/', verbose_name='фото категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='слаг')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname_contact', models.CharField(max_length=25, verbose_name='Имя контакта')),
                ('email_contact', models.EmailField(max_length=30, verbose_name='email контакта')),
                ('text_contact', models.TextField(max_length=350, verbose_name='Сообщение контакта')),
                ('phone_contact', models.CharField(max_length=12, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='название')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='слаг')),
                ('description', models.TextField(blank=True, null=True, verbose_name='описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='цена')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product/%Y/%m/%d/', verbose_name='фото')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='uploads/', verbose_name='миниатюра')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='дата добавления')),
                ('set_products', models.CharField(default='Полная', max_length=100, verbose_name='Комплектация')),
                ('video', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/', verbose_name='видео')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
                'ordering': ('-date_added',),
            },
        ),
    ]
