# Generated by Django 3.2.16 on 2024-08-07 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='phone_contact',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='text_contact',
        ),
    ]
